import React from 'react'
import { Avatar } from '../Avatar'
import { Button } from '../Button'
import styles from './Profile.module.scss'
import clsx from 'clsx'
import Head from 'next/head'
import { useSelector } from 'react-redux'
import { selectUserData } from '@/redux/selectors'

interface ProfileProps {
  fullName: string
  userName: string
  avatarUrl: string
  about: string
}

const Profile: React.FC<ProfileProps> = ({ fullName, userName, avatarUrl, about }) => {
  const userData = useSelector(selectUserData)

  // if (!userData) {
  //   return <h2>Loading...</h2>
  // }

  return (
    <>
      <Head>
        <title>Clubhouse: Drop-in audio chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="d-flex justify-content-between mb-40">
        <div className="d-flex align-items-center">
          <Avatar width="100px" height="100px" src={avatarUrl} letters="N" />
          <div className="d-flex flex-column ml-20 mr-20">
            <h1 className="mt-0 mb-0">{fullName}</h1>
            <h2 className={clsx(styles.username, 'mt-0 mb-0')}>@{userName}</h2>
          </div>

          <Button color="blue" className={styles.button}>
            <>Follow</>
          </Button>
        </div>

        <div className={styles.followInfo}>
          <div>
            <h2>2</h2>
            <span>followers</span>
          </div>
          <div>
            <h2>0</h2>
            <span>following</span>
          </div>
        </div>
      </div>
      <p className={styles.about}>{about}</p>
    </>
  )
}

export default Profile
