import { NextPage } from 'next'
import React, { ReactNode } from 'react'
import Head from 'next/head'
import { Header } from '../Header'

interface ILayout {
  children: ReactNode
}

const Layout: NextPage<ILayout> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Clubhouse: Drop-in audio chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />

      {children}
    </>
  )
}

export default Layout

/* 
import { NextPage } from 'next'
import React, { ReactNode } from 'react'
import Head from 'next/head'
import { Header } from '../Header'
import { useAppDispatch } from '@/redux/store'
import axios from 'axios'
import Cookies from 'js-cookie'
import { setUserData } from '@/redux/slises/authSlise'
import { useDispatch } from 'react-redux'

const Layout: NextPage<ILayout> = ({ children }) => {
  const dispatch = useDispatch()

  React.useEffect(() => {
    const fetchMe = async () => {
      const cookies = Cookies.get()
      const token = cookies.token
      if (token) {
        axios.defaults.headers.Authorization = `Bearer ${token}`
        axios.defaults.baseURL = 'http://localhost:3001'

        const { data } = await axios.get('/auth/me')

        dispatch(setUserData(data))
      }
    }

    fetchMe()
  }, [])

  return <>{children}</>
}

export default Layout

*/
