import React from 'react'
import Link from 'next/link'
import { GetServerSideProps, GetServerSidePropsContext } from 'next'

import Room from '@/components/Room'
import { Header } from '@/components/Header'
import { ConversationCard } from '../rooms'
import { Api } from '@/api'
import Head from 'next/head'
import { selectAuthUser } from '@/redux/selectors'
import { useSelector } from 'react-redux'

interface RoomPageProps {
  room: ConversationCard
}

const RoomPage: React.FC<RoomPageProps> = ({ room }) => {
  return (
    <>
      <Head>
        <title>Clubhouse: Drop-in audio chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />

      <div className="container">
        <Link href="/rooms" className="d-ib cup">
          <img src="/static/back-arrow.svg" alt="back" />
          <h3 className="ml-10 d-ib">All rooms</h3>
        </Link>
      </div>

      <Room title={room.title} users={[]} />
    </>
  )
}

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  try {
    const roomId = ctx.query.id

    if (!roomId || typeof roomId !== 'string') {
      return {
        props: {},
      }
    }
    const room = await Api(ctx).room.getOneRoom(roomId)

    return {
      props: { room },
    }
  } catch (error) {
    console.log(error)
    return {
      props: {},
      redirect: {
        destination: '/rooms',
        permanent: false,
      },
    }
  }
}

export default RoomPage
